version: '1.0'

services:
  dbpg:
    container_name: test-dbpg
    image: postgres:12
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgres/data

  redis:
      container_name: test-redis
      image: redis:7-alpine
      ports:
        - ${CACHE_PORT}:6379
      volumes:
        - redisdata:/data
      networks:
        - webservice

volumes:
  redisdata:
  pgdata:

networks:
  webservice: