export enum ModuleName {
  USER = 'user',
  ADMIN = 'admin',
  BRAND = 'brand',
  PRODUCT = 'product',
  CATEGORY = 'category',
  COIN_EVENT = 'coin event',
  COIN_REDEEM = 'coin reddem',
  COIN_REWARD_CATEGORY = 'coin reward category',
  COIN_REWARD = 'coin reward',
  COIN_SETTING = 'coin setting',
  FLASH_SALE = 'flash sale',
  ORDER = 'order',
  NOTIFICATION_TEMPLATE = 'notification template',
  PAYMENT = 'payment',
  PRODUCT_BUNDLING = 'product bundling',
  ROLE = 'role',
  SLIDER_BANNER = 'slider banner',
  SUB_CATEGORY = 'sub category',
  SUB_SUB_CATEGORY = 'sub sub category',
  UPDATE_FEATURE = 'update feature',
  LEADERBOARD = 'leaderboard',
  SETTING = 'setting',
}
